# Generated by Django 3.1.4 on 2020-12-24 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование товара')),
                ('date_rec', models.DateField(verbose_name='Дата поступления')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='Цена')),
                ('u_measure', models.CharField(max_length=30, verbose_name='Единица измерения')),
                ('name_provider', models.CharField(max_length=255, verbose_name='Поставщик')),
            ],
        ),
    ]
